services:
  uptime-push:
    build: .
    container_name: uptime-push
    restart: always
    environment:
      # Set your Uptime Kuma push URL here
      PUSH_URL: "uptime-url-here"

      # Optional: heartbeat interval (seconds)
      INTERVAL: "30"

